sudo: false
cache: bundler
script: bundle exec rake spec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head

matrix:
  include:
    - rvm: rbx-3
      env: RBX_RUBY_COMPAT=2.2.2 RBX_VERSION=3.40
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
